<?php

declare(strict_types=1);

namespace App\Repositories;

use App\Services\Memos\Memo;
use Illuminate\Database\DatabaseManager;
use RuntimeException;
use stdClass;

/**
 * SQL for the memos table. Nothing above this namespace imports PDO or writes a
 * query, and no ORM is involved -- Eloquent is unused across this project per
 * MEMO-05, and the schema belongs to db/migrations rather than to PHP.
 *
 * Not final, unlike HealthRepository, and only for one reason: the feature suite
 * substitutes a fake for it. `php artisan test` runs against sqlite in memory (see
 * phpunit.xml) and every query below is Postgres-specific -- to_jsonb, to_char,
 * INSERT ... RETURNING over a table with a generated tsvector column -- so the
 * alternative to a seam here is a second, drifting definition of the schema in the
 * test suite. HealthEndpointTest gets to stay honest by misconfiguring the real
 * connection because "the database is unreachable" is a driver-independent
 * outcome; "the list came back newest first" is not. MEMO-25 owns the suite that
 * runs these statements against a real Postgres.
 */
class MemoRepository
{
    /**
     * The projection, shared by both statements below so the create response and
     * the list rows cannot drift apart.
     *
     * Enumerated rather than `*`, and that is a rule on this table rather than a
     * preference: `search_vector` is part of `*` and is the largest thing on the
     * row, so shipping it would put a full stemmed copy of every transcript into a
     * response nobody reads it from.
     *
     * Two conversions happen in SQL rather than in PHP:
     *
     *   * to_jsonb(tags), because the driver hands back Postgres' `{a,b}` array
     *     literal as an undifferentiated string and its quoting rules are not worth
     *     reimplementing. Memo::fromRow only has to json_decode.
     *   * to_char on created_at, so the wire format is one fixed, unambiguous
     *     string -- milliseconds, UTC, RFC 3339 -- instead of whatever the server's
     *     DateStyle and the session TimeZone would have produced for PHP to reparse.
     *     `AT TIME ZONE 'UTC'` is what makes the literal Z true.
     *
     * That second one is aliased `created_at_iso` rather than `created_at`, and the
     * ugly name is load-bearing. ORDER BY resolves a bare name against the output
     * column labels before the table's columns, so with the obvious alias the
     * `ORDER BY created_at DESC` in recent() below silently stops meaning the
     * timestamp column and starts meaning this formatted string. Caught here by
     * reading the plan rather than by reasoning: at 5,000 rows the aliased version
     * plans a Seq Scan plus a Sort on the to_char expression, while the same query
     * with the alias renamed is an Index Scan using memos_created_idx. It is not even
     * wrong -- this format sorts identically to the timestamp, so the rows come back
     * in the right order and only the index is quietly lost -- which is exactly why
     * it needs a name that cannot collide instead of a comment asking for care.
     * `ORDER BY memos.created_at DESC` also fixes it, and was rejected: it restores
     * the index scan by relying on the same subtlety, one dropped qualifier away from
     * regressing.
     *
     * This paragraph used to end by saying MEMO-19 would add a ts_rank ordering here and
     * should not have to know any of the above. It did have to know, and then it did not
     * add one -- search() below orders by created_at too, for reasons measured there. So
     * the aliasing still matters, and now it matters to both statements rather than to
     * one of them plus a future one.
     */
    private const COLUMNS = <<<'SQL'
        id,
        source,
        status,
        transcript,
        title,
        summary,
        to_jsonb(tags) AS tags,
        duration_ms,
        last_error,
        to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') AS created_at_iso
        SQL;

    public function __construct(private readonly DatabaseManager $db) {}

    /**
     * One statement, and the row it just wrote comes back with it.
     *
     * RETURNING is what lets POST answer 201 with the full row without a follow-up
     * SELECT -- which is not merely a saved round trip: `created_at` is a column
     * default, so without RETURNING the response would either omit it or carry a
     * timestamp PHP invented that does not match the one in the table.
     *
     * The id is generated by the caller rather than by the database. 001_init.sql
     * declares `id uuid PRIMARY KEY` with no DEFAULT precisely so that omitting it
     * is a not-null violation instead of a silently unordered v4.
     *
     * The audio pair defaults to null rather than being required of every caller,
     * because "this memo has no recording" is what a text memo is -- the same reading
     * `transcript IS NULL` gets on the other side. Both columns are still named in the
     * statement and bound as NULL, so there is one INSERT rather than two shapes of
     * one.
     *
     * They travel together and are not independently optional: `audio_mime` describes
     * `audio_path`, and a row carrying one without the other would be either a blob
     * nothing can serve (MEMO-23 reads the mime to answer with) or a mime for a file
     * that does not exist. Nothing here enforces the pairing -- MemoService is the only
     * caller and passes both -- and it is not worth a CHECK constraint on a table
     * written by one statement in one file.
     *
     * @param  string  $source  Memo::SOURCE_TEXT with a transcript and no audio, or
     *                          Memo::SOURCE_VOICE with audio and a null transcript.
     * @param  ?string  $audioPath  A storage *key*, relative to AUDIO_DIR -- never an
     *                              absolute path. See App\Contracts\AudioStorage.
     */
    public function insert(
        string $id,
        string $source,
        string $status,
        ?string $transcript,
        ?string $audioPath = null,
        ?string $audioMime = null,
    ): Memo {
        // selectFromWriteConnection, not select(). This is a write that returns
        // rows, and select() is the read path -- it is the same connection today
        // because config/database.php configures no read/write split, but the day
        // one is added a plain select() here would send an INSERT to a replica.
        $rows = $this->db->connection()->selectFromWriteConnection(
            'INSERT INTO memos (id, source, status, transcript, audio_path, audio_mime)'
                .' VALUES (?, ?, ?, ?, ?, ?) RETURNING '.self::COLUMNS,
            [$id, $source, $status, $transcript, $audioPath, $audioMime],
        );

        $row = $rows[0] ?? null;

        if (! $row instanceof stdClass) {
            // Unreachable via Postgres: an INSERT ... RETURNING that inserts a row
            // returns it, and anything that stopped the insert -- the CHECK
            // constraints on source and status, a duplicate id -- raises instead.
            // Asserted rather than assumed because the alternative is a TypeError
            // from Memo::fromRow, which reads as a mapping bug rather than as a
            // write that did not happen.
            throw new RuntimeException("INSERT of memo {$id} returned no row.");
        }

        return Memo::fromRow($row);
    }

    /**
     * Newest first, which is the only order this endpoint offers.
     *
     * ORDER BY created_at DESC is served by memos_created_idx, declared DESC in
     * 001_init.sql for exactly this query -- confirmed as `Index Scan using
     * memos_created_idx` on a 5,000-row table, and see COLUMNS for the aliasing that
     * turns it back into a Seq Scan.
     *
     * No tiebreaker, and not because UUIDv7 ids happen to agree with created_at --
     * that agreement does nothing for a tie, since without id in the ORDER BY
     * Postgres does not order tied rows by it at all. It is that a tie needs two
     * memos with the same created_at, and created_at defaults to now(), which is
     * transaction-start time: two rows can only share one if they were inserted in
     * the same transaction. This API inserts exactly one row per request. Confirmed
     * from the other side too -- 5,010 rows written one-per-statement had 5,008
     * distinct timestamps, the two duplicates being a fixture that did insert several
     * in one transaction. Adding `, id DESC` for the unreachable case is not free
     * either: it plans an Incremental Sort on top of the index scan.
     *
     * $limit is bound rather than interpolated. Laravel binds a PHP int as
     * PDO::PARAM_INT, which is what a parameterised LIMIT needs; the value reaching
     * here has already been validated by ListMemosRequest, so the bound parameter
     * is defence in depth rather than the only check.
     *
     * @return list<Memo>
     */
    public function recent(int $limit): array
    {
        $rows = $this->db->connection()->select(
            'SELECT '.self::COLUMNS.' FROM memos ORDER BY created_at DESC LIMIT ?',
            [$limit],
        );

        return $this->hydrate($rows);
    }

    /**
     * The same page, filtered by text.
     *
     * Three OR'd predicates, and Postgres serves all three from an index -- confirmed as
     * a BitmapOr over memos_search_idx, memos_trgm_idx and memos_claim_idx on a 5,006-row
     * table, with bound parameters rather than literals so the plan is the one this
     * statement actually gets.
     *
     * **1. The full-text match.** `websearch_to_tsquery`, not `to_tsquery` or
     * `plainto_tsquery`. It gives quoted phrases and minus-exclusion for free -- `"call
     * the dentist"` compiles to `'call' <2> 'dentist'` and `dentist -thursday` to
     * `'dentist' & !'thursday'` -- and, unlike to_tsquery, it never raises on input a
     * human typed. That is the part that matters here, because the input is a search box:
     * `to_tsquery('english', 'dentist &')` is `ERROR: no operand in tsquery` and
     * `'a | | b'` is `ERROR: syntax error in tsquery`, both of which would be a 500 for a
     * half-typed query. websearch_to_tsquery answers `'dentist'` and `'b'`.
     *
     * A query of nothing but punctuation or stop words compiles to the empty tsquery,
     * which matches no row -- `@@` returns false, not null, so it does not poison the OR.
     * The ILIKE arm is what keeps such a query useful.
     *
     * **2. The ILIKE fallback,** for the two cases the tsvector cannot reach: a partial
     * word, and a run-together token. Both are spelled out in 001_init.sql next to the
     * index that serves them.
     *
     * Not the similarity operator, and this is the trap worth naming: `%` looks like the
     * right tool and silently matches nothing. Against a 751-character transcript
     * containing "reorganise", `similarity('reorg', transcript)` is 0.0129 -- similarity
     * divides by the union of both trigram sets, so a long transcript drives any short
     * needle towards zero -- and the default threshold is 0.3, so `'reorg' % transcript`
     * is false. `word_similarity` scores the same pair 0.8333 and would work, but it
     * reads its threshold from a session GUC (`set_limit`/`show_limit`), which makes the
     * result depend on connection state this application never sets. ILIKE has no
     * threshold to be wrong about, and it is the operator whose semantics match what
     * somebody typing five characters means: this substring, exactly.
     *
     * Only `transcript`, matching the one gin_trgm_ops index there is. Extending the
     * fallback to `title` and `summary` was measured and rejected: with no trigram index
     * on either, the added OR arms drop the whole statement to a Seq Scan over every row.
     * Little is lost -- both columns are generated from the transcript by MEMO-21, so a
     * partial word in a title is almost always a partial word in the transcript as well
     * -- and the full-text arm covers them exactly, since search_vector spans title,
     * summary, transcript and tags.
     *
     * **3. The in-flight pin.** A memo still being transcribed has no transcript, so it
     * matches nothing and would vanish from the list the moment a filter was active --
     * right after the user recorded it. Memo::inFlightStatuses() says which statuses that
     * covers and why 'failed' is not one of them.
     *
     * Worth knowing about the pin: a *text* memo is inserted with its transcript already
     * set, so it is searchable while queued and does not need the pin to be visible. What
     * the pin buys it is the enrichment window -- its title, summary and tags land later,
     * so a query that only its future tags would match finds it from the start rather
     * than when the worker gets to it. The voice path (MEMO-11) is the case the pin is
     * really for.
     *
     * **Ordering: created_at DESC, the same as recent().** Both 001_init.sql and COLUMNS
     * above expected a ts_rank ordering here. Three measurements against the schema said
     * otherwise, and the third is decisive:
     *
     *   * ts_rank cannot rank the ILIKE half of this predicate. A row matched only by
     *     substring does not match the tsquery, so its rank is exactly 0 -- the same trap
     *     001_init.sql documented for tag-only rows under ts_rank_cd, one arm further
     *     along. Ordering by rank would bury every partial-word hit beneath every
     *     full-text hit.
     *   * where ts_rank does apply, it barely separates anything: 0.0760 for a transcript
     *     match against 0.0608 for a tag-only match on the same query. It encodes which
     *     column matched more than how relevant the memo is.
     *   * rank ordering puts the pinned in-flight rows *last*. They score 0 like every
     *     other non-tsquery match, so `ORDER BY rank DESC` sorts them below every hit --
     *     measured, both of them under both dentist memos -- and with a LIMIT they are
     *     dropped outright once there are `limit` matches. The memo the pin exists to
     *     keep on screen is the first thing rank ordering throws away.
     *
     * created_at DESC needs no special term for any of that: a memo recorded seconds ago is
     * the newest row there is, so it sorts to the top on its own, and the list keeps one
     * order whether or not a filter is active.
     *
     * What the pin does not survive is the LIMIT, and only for a memo that has been
     * in-flight long enough to stop being near the top -- one stuck behind a stopped worker
     * for days. Measured: with 60 newer matches and `limit=50`, a ten-day-old queued memo is
     * not in the response. Left as is, because the unfiltered list drops that same row for
     * the same reason, so the filter is not hiding anything the app would otherwise show,
     * and pinning it regardless would mean a UNION with a limit of its own -- which then
     * makes a stalled queue able to crowd the matches out of the page instead. The window
     * the pin exists for is seconds long, and it is comfortably inside this.
     *
     * @return list<Memo>
     */
    public function search(string $query, int $limit): array
    {
        // Built from the constant rather than written out, so adding a status to
        // Memo::inFlightStatuses() cannot leave the placeholder count behind and turn a
        // lifecycle change into a bound-parameter mismatch.
        $inFlight = implode(', ', array_fill(0, count(Memo::inFlightStatuses()), '?'));

        $rows = $this->db->connection()->select(
            'SELECT '.self::COLUMNS
                ." FROM memos\n"
                ."WHERE (search_vector @@ websearch_to_tsquery('english', ?) OR transcript ILIKE ?)\n"
                ."   OR status IN ({$inFlight})\n"
                ."ORDER BY created_at DESC\n"
                .'LIMIT ?',
            [
                $query,
                self::likePattern($query),
                ...Memo::inFlightStatuses(),
                $limit,
            ],
        );

        return $this->hydrate($rows);
    }

    /**
     * Wraps a user's query in `%` for a substring ILIKE, escaping the three characters
     * that would otherwise be pattern syntax.
     *
     * This is not hygiene -- the query is a bound parameter and was never an injection
     * risk. It is that `%` and `_` are wildcards inside a LIKE pattern, so without this
     * the user's own punctuation quietly changes what they searched for. Measured against
     * the fixture: unescaped, `q=50%` builds the pattern `%50%%`, whose trailing pair
     * reads as "anything", and it matched **102 rows** where one memo mentions a margin of
     * 50%. `_` is the quieter version of the same bug -- it matches exactly one character,
     * so `created_at` and `createdXat` are the same query.
     *
     * Backslash is escaped first and for a different reason: it is LIKE's default escape
     * character, so a lone trailing `\` in the query would leave a dangling escape and
     * make Postgres raise on the pattern. Order matters -- doing `%` and `_` first would
     * then escape the backslashes this step just added.
     *
     * The escaped pattern is still index-driven; `%created\_%` plans as a Bitmap Index
     * Scan on memos_trgm_idx exactly as the unescaped one does, so this costs nothing but
     * correctness. What it cannot fix is that a pattern with fewer than three
     * non-wildcard characters has no trigram to look up and falls back to a Seq Scan --
     * `%re%` scans all 5,006 rows. That is a property of trigram indexes rather than of
     * this function, and it is bounded by MAX_LIMIT and the size of this table.
     *
     * Public and static so it can be tested for what it returns rather than for what
     * Postgres does with it: LikePatternTest asserts the pattern this builds for `50%`, so
     * what is pinned is the escaping that prevents those 102 rows rather than the count
     * itself, which would need a live database to reach.
     */
    public static function likePattern(string $query): string
    {
        return '%'.str_replace(['\\', '%', '_'], ['\\\\', '\\%', '\\_'], $query).'%';
    }

    /**
     * @param  list<stdClass>  $rows
     * @return list<Memo>
     */
    private function hydrate(array $rows): array
    {
        return array_values(array_map(
            static fn (stdClass $row): Memo => Memo::fromRow($row),
            $rows,
        ));
    }
}
