<?php

declare(strict_types=1);

namespace App\Repositories;

use App\Services\Memos\Memo;
use Illuminate\Database\DatabaseManager;
use RuntimeException;
use stdClass;

/**
 * SQL for the memos table. Nothing above this namespace imports PDO or writes a
 * query, and no ORM is involved -- Eloquent is unused across this project per
 * MEMO-05, and the schema belongs to db/migrations rather than to PHP.
 *
 * Not final, unlike HealthRepository, and only for one reason: the feature suite
 * substitutes a fake for it. `php artisan test` runs against sqlite in memory (see
 * phpunit.xml) and every query below is Postgres-specific -- to_jsonb, to_char,
 * INSERT ... RETURNING over a table with a generated tsvector column -- so the
 * alternative to a seam here is a second, drifting definition of the schema in the
 * test suite. HealthEndpointTest gets to stay honest by misconfiguring the real
 * connection because "the database is unreachable" is a driver-independent
 * outcome; "the list came back newest first" is not. MEMO-25 owns the suite that
 * runs these statements against a real Postgres.
 */
class MemoRepository
{
    /**
     * The projection, shared by both statements below so the create response and
     * the list rows cannot drift apart.
     *
     * Enumerated rather than `*`, and that is a rule on this table rather than a
     * preference: `search_vector` is part of `*` and is the largest thing on the
     * row, so shipping it would put a full stemmed copy of every transcript into a
     * response nobody reads it from.
     *
     * Two conversions happen in SQL rather than in PHP:
     *
     *   * to_jsonb(tags), because the driver hands back Postgres' `{a,b}` array
     *     literal as an undifferentiated string and its quoting rules are not worth
     *     reimplementing. Memo::fromRow only has to json_decode.
     *   * to_char on created_at, so the wire format is one fixed, unambiguous
     *     string -- milliseconds, UTC, RFC 3339 -- instead of whatever the server's
     *     DateStyle and the session TimeZone would have produced for PHP to reparse.
     *     `AT TIME ZONE 'UTC'` is what makes the literal Z true.
     *
     * That second one is aliased `created_at_iso` rather than `created_at`, and the
     * ugly name is load-bearing. ORDER BY resolves a bare name against the output
     * column labels before the table's columns, so with the obvious alias the
     * `ORDER BY created_at DESC` in recent() below silently stops meaning the
     * timestamp column and starts meaning this formatted string. Caught here by
     * reading the plan rather than by reasoning: at 5,000 rows the aliased version
     * plans a Seq Scan plus a Sort on the to_char expression, while the same query
     * with the alias renamed is an Index Scan using memos_created_idx. It is not even
     * wrong -- this format sorts identically to the timestamp, so the rows come back
     * in the right order and only the index is quietly lost -- which is exactly why
     * it needs a name that cannot collide instead of a comment asking for care.
     * `ORDER BY memos.created_at DESC` also fixes it, and was rejected: it restores
     * the index scan by relying on the same subtlety, one dropped qualifier away from
     * regressing. MEMO-19 adds a ts_rank ordering to this query and should not have
     * to know any of this.
     */
    private const COLUMNS = <<<'SQL'
        id,
        source,
        status,
        transcript,
        title,
        summary,
        to_jsonb(tags) AS tags,
        duration_ms,
        last_error,
        to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') AS created_at_iso
        SQL;

    public function __construct(private readonly DatabaseManager $db) {}

    /**
     * One statement, and the row it just wrote comes back with it.
     *
     * RETURNING is what lets POST answer 201 with the full row without a follow-up
     * SELECT -- which is not merely a saved round trip: `created_at` is a column
     * default, so without RETURNING the response would either omit it or carry a
     * timestamp PHP invented that does not match the one in the table.
     *
     * The id is generated by the caller rather than by the database. 001_init.sql
     * declares `id uuid PRIMARY KEY` with no DEFAULT precisely so that omitting it
     * is a not-null violation instead of a silently unordered v4.
     *
     * @param  string  $source  Memo::SOURCE_TEXT today; MEMO-11 adds the voice path,
     *                          which also writes audio_path and audio_mime and passes
     *                          a null transcript.
     */
    public function insert(string $id, string $source, string $status, ?string $transcript): Memo
    {
        // selectFromWriteConnection, not select(). This is a write that returns
        // rows, and select() is the read path -- it is the same connection today
        // because config/database.php configures no read/write split, but the day
        // one is added a plain select() here would send an INSERT to a replica.
        $rows = $this->db->connection()->selectFromWriteConnection(
            'INSERT INTO memos (id, source, status, transcript) VALUES (?, ?, ?, ?) RETURNING '.self::COLUMNS,
            [$id, $source, $status, $transcript],
        );

        $row = $rows[0] ?? null;

        if (! $row instanceof stdClass) {
            // Unreachable via Postgres: an INSERT ... RETURNING that inserts a row
            // returns it, and anything that stopped the insert -- the CHECK
            // constraints on source and status, a duplicate id -- raises instead.
            // Asserted rather than assumed because the alternative is a TypeError
            // from Memo::fromRow, which reads as a mapping bug rather than as a
            // write that did not happen.
            throw new RuntimeException("INSERT of memo {$id} returned no row.");
        }

        return Memo::fromRow($row);
    }

    /**
     * Newest first, which is the only order this endpoint offers.
     *
     * ORDER BY created_at DESC is served by memos_created_idx, declared DESC in
     * 001_init.sql for exactly this query -- confirmed as `Index Scan using
     * memos_created_idx` on a 5,000-row table, and see COLUMNS for the aliasing that
     * turns it back into a Seq Scan. No tiebreaker is added: it would cost a sort
     * node on top of the index scan, and ids are UUIDv7, so id order and created_at
     * order already agree.
     *
     * $limit is bound rather than interpolated. Laravel binds a PHP int as
     * PDO::PARAM_INT, which is what a parameterised LIMIT needs; the value reaching
     * here has already been validated by ListMemosRequest, so the bound parameter
     * is defence in depth rather than the only check.
     *
     * @return list<Memo>
     */
    public function recent(int $limit): array
    {
        $rows = $this->db->connection()->select(
            'SELECT '.self::COLUMNS.' FROM memos ORDER BY created_at DESC LIMIT ?',
            [$limit],
        );

        return array_values(array_map(
            static fn (stdClass $row): Memo => Memo::fromRow($row),
            $rows,
        ));
    }
}
