<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Http\Requests\ListMemosRequest;
use App\Http\Requests\StoreMemoRequest;
use App\Repositories\MemoRepository;
use App\Services\Memos\Memo;
use Tests\Support\FakeMemoRepository;
use Tests\TestCase;

/**
 * The decisions MEMO-06 makes that do not depend on the driver. The SQL itself --
 * ordering, to_jsonb over a real text[], the generated tsvector column -- needs a
 * live Postgres and belongs to MEMO-25; see FakeMemoRepository for why the seam is
 * drawn here.
 */
final class MemoEndpointsTest extends TestCase
{
    private FakeMemoRepository $repository;

    protected function setUp(): void
    {
        parent::setUp();

        $this->repository = new FakeMemoRepository;
        $this->app->instance(MemoRepository::class, $this->repository);
    }

    public function test_posting_text_writes_a_queued_text_memo_and_returns_it_with_its_id(): void
    {
        $response = $this->postJson('/api/memos', ['text' => 'Call the dentist on Tuesday']);

        $response->assertCreated()
            ->assertJsonPath('memo.source', 'text')
            // queued, not ready. The worker still owes this row its enrichment pass.
            ->assertJsonPath('memo.status', 'queued')
            ->assertJsonPath('memo.transcript', 'Call the dentist on Tuesday')
            ->assertJsonPath('memo.title', null)
            ->assertJsonPath('memo.tags', [])
            ->assertJsonPath('memo.duration_ms', null)
            // The full field set, asserted as a whole: MEMO-18 replaces polled rows
            // by id against the object this response produced, so a field appearing
            // in one and not the other is the bug that assertion exists to catch.
            ->assertJsonStructure([
                'memo' => [
                    'id', 'source', 'status', 'transcript', 'title',
                    'summary', 'tags', 'duration_ms', 'last_error', 'created_at',
                ],
            ]);

        $this->assertCount(1, $this->repository->inserted);
        $insert = $this->repository->inserted[0];

        $this->assertSame(Memo::SOURCE_TEXT, $insert['source']);
        $this->assertSame(Memo::STATUS_QUEUED, $insert['status']);
        // The typed text is the transcript, which is what tells the worker no
        // transcription is owed.
        $this->assertSame('Call the dentist on Tuesday', $insert['transcript']);

        // The id was generated by PHP and travelled back out on the 201 -- the whole
        // reason 001_init.sql gives `id` no column default.
        $this->assertSame($insert['id'], $response->json('memo.id'));
        $this->assertSame('7', $insert['id'][14], 'The id must be a UUIDv7.');
    }

    public function test_a_missing_blank_or_oversized_text_is_rejected_and_writes_nothing(): void
    {
        $this->postJson('/api/memos', [])
            ->assertStatus(422)
            ->assertJsonValidationErrors('text');

        // Whitespace only. Trimmed before the rules run, so `min:1` is what refuses
        // it -- a memo whose transcript is three spaces would reach the worker,
        // transcribe to nothing and enrich to nothing.
        $this->postJson('/api/memos', ['text' => "  \n\t "])
            ->assertStatus(422)
            ->assertJsonValidationErrors('text');

        $this->postJson('/api/memos', ['text' => str_repeat('a', StoreMemoRequest::MAX_TEXT_LENGTH + 1)])
            ->assertStatus(422)
            ->assertJsonValidationErrors('text');

        // A rejected request must not have reached the database.
        $this->assertSame([], $this->repository->inserted);
    }

    public function test_a_null_byte_inside_the_text_is_refused_rather_than_silently_truncated(): void
    {
        // The bug this pins: libpq passes bound parameters as C strings, so without
        // this rule the value is cut at the first NUL before Postgres -- which would
        // have rejected it -- ever sees it. Confirmed against a live database before
        // the rule existed: this exact body answered 201 with a transcript of "a".
        $this->postJson('/api/memos', ['text' => "a\0b"])
            ->assertStatus(422)
            ->assertJsonValidationErrors('text');

        $this->assertSame([], $this->repository->inserted);

        // A NUL at either edge was already handled, and by something incidental --
        // PHP's default trim charlist contains "\0", so prepareForValidation strips
        // it and `required` refuses what is left. Asserted so that a later change to
        // that trim cannot quietly reopen the interior case's smaller cousin.
        $this->postJson('/api/memos', ['text' => "\0"])
            ->assertStatus(422)
            ->assertJsonValidationErrors('text');
    }

    public function test_surrounding_whitespace_is_trimmed_from_the_stored_transcript(): void
    {
        $this->postJson('/api/memos', ['text' => '   Milk, eggs, bread   '])
            ->assertCreated()
            ->assertJsonPath('memo.transcript', 'Milk, eggs, bread');

        $this->assertSame('Milk, eggs, bread', $this->repository->inserted[0]['transcript']);
    }

    public function test_the_length_cap_counts_characters_rather_than_bytes(): void
    {
        // Exactly at the cap in characters, four times over it in bytes. Rejecting
        // this would make the limit mean something different for anyone not writing
        // in ASCII.
        $this->postJson('/api/memos', ['text' => str_repeat('あ', StoreMemoRequest::MAX_TEXT_LENGTH)])
            ->assertCreated();
    }

    public function test_listing_renders_every_field_and_keeps_the_order_it_was_given(): void
    {
        $this->repository->rows = [
            $this->memo('019fb4ef-0d71-7011-b678-0cb4004dc2a7', 'the newer one'),
            $this->memo('019fb4ee-0d71-7011-b678-0cb4004dc2a7', 'the older one'),
        ];

        $response = $this->getJson('/api/memos');

        $response->assertOk()
            ->assertJsonCount(2, 'memos')
            ->assertJsonPath('memos.0.transcript', 'the newer one')
            ->assertJsonPath('memos.1.transcript', 'the older one')
            ->assertJsonPath('memos.0.tags', ['dentist', 'health'])
            ->assertJsonPath('memos.0.duration_ms', 4200)
            ->assertJsonPath('memos.0.last_error', null)
            ->assertJsonPath('memos.0.created_at', '2026-07-31T09:00:00.000Z');

        // Newest-first is `ORDER BY created_at DESC` in the repository, verified
        // against a live Postgres rather than here: this asserts only that nothing
        // between the query and the JSON reorders the rows.
        $this->assertSame(ListMemosRequest::DEFAULT_LIMIT, $this->repository->lastLimit);
    }

    public function test_a_polled_list_is_never_cached(): void
    {
        $response = $this->getJson('/api/memos');

        $this->assertStringContainsString(
            'no-store',
            (string) $response->headers->get('Cache-Control'),
        );
    }

    public function test_limit_is_honoured_bounded_and_defaulted(): void
    {
        $this->getJson('/api/memos?limit=10')->assertOk();
        $this->assertSame(10, $this->repository->lastLimit);

        // Set but empty is "unset", the same reading App\Support\Env applies to the
        // environment: a query string built with no limit chosen must not 422.
        $this->getJson('/api/memos?limit=')->assertOk();
        $this->assertSame(ListMemosRequest::DEFAULT_LIMIT, $this->repository->lastLimit);

        // Rejected rather than clamped. A clamped 5000 answers 200 with 200 rows and
        // reads as "there are only 200 memos".
        foreach (['0', '-1', 'abc', '10.5', (string) (ListMemosRequest::MAX_LIMIT + 1)] as $limit) {
            $this->getJson("/api/memos?limit={$limit}")
                ->assertStatus(422)
                ->assertJsonValidationErrors('limit');
        }
    }

    public function test_a_query_reaches_the_search_statement_exactly_as_it_was_typed(): void
    {
        // Whatever the query means is decided by websearch_to_tsquery and by the ILIKE
        // pattern, both in SQL. Nothing between the query string and the bound parameter
        // may rewrite it -- stripping the quotes from a phrase or the minus from an
        // exclusion here would silently turn the two features the search advertises into
        // a bag of words.
        foreach (['dentist', '"call the dentist"', 'dentist -thursday', 'reorg', '50%'] as $query) {
            $this->getJson('/api/memos?q='.urlencode($query))->assertOk();

            $this->assertTrue($this->repository->searched);
            $this->assertSame($query, $this->repository->lastQuery);
        }
    }

    public function test_the_query_is_echoed_back_so_a_stale_response_can_be_discarded(): void
    {
        // Searching is debounced and polled, so a response can arrive after the box has
        // moved on. The client compares this key to decide whether the rows it just
        // received still belong on screen.
        $this->getJson('/api/memos?q=dentist')
            ->assertOk()
            ->assertJsonPath('query', 'dentist');

        // Always present, so the client reads one key rather than branching on whether it
        // exists.
        $this->getJson('/api/memos')
            ->assertOk()
            ->assertJsonPath('query', null);
    }

    public function test_a_blank_query_is_no_filter_rather_than_a_filter_matching_everything(): void
    {
        // Three spellings of "the user has not typed anything". The frontend's search box
        // is empty most of the time, so these are the ordinary request: `?q=` is what a
        // query string built around an empty box looks like, and %20 is what one space in
        // it looks like.
        foreach (['/api/memos', '/api/memos?q=', '/api/memos?q=%20%20'] as $url) {
            $this->getJson($url)->assertOk()->assertJsonPath('query', null);

            // The unfiltered statement, which is the one with the index scan. A filter
            // matching everything would answer the same rows and lose that plan.
            $this->assertFalse($this->repository->searched);
            $this->assertNull($this->repository->lastQuery);
        }
    }

    public function test_a_query_that_is_falsy_as_a_string_is_still_a_query(): void
    {
        // '0' is falsy in PHP and in JavaScript, so both halves of this feature have a
        // truthiness test one refactor away from turning a search for "0" into no filter at
        // all -- answering the entire list and looking like the search silently broke.
        // Reachable: "0" is what you type looking for a memo about a zero.
        $this->getJson('/api/memos?q=0')
            ->assertOk()
            ->assertJsonPath('query', '0');

        $this->assertTrue($this->repository->searched);
        $this->assertSame('0', $this->repository->lastQuery);
    }

    public function test_a_rejected_filter_says_so_in_words_a_reader_can_act_on(): void
    {
        // The frontend renders this message verbatim (web/src/api/memos.js), and a paste
        // into the filter box is how a 422 gets reached without meaning to. Unnamed, the
        // field reads "The q field must not be greater than 200 characters." -- a sentence
        // about a query-string parameter, shown to somebody looking at a box labelled
        // "Filter memos".
        $response = $this->getJson('/api/memos?q='.str_repeat('a', ListMemosRequest::MAX_QUERY_LENGTH + 1));

        $response->assertStatus(422);

        $this->assertStringContainsString('filter', (string) $response->json('message'));
        $this->assertStringNotContainsString('q field', (string) $response->json('message'));
    }

    public function test_surrounding_whitespace_is_trimmed_from_the_query(): void
    {
        // So the ILIKE pattern is `%dentist%` rather than `%  dentist  %`, which would
        // match nothing. Trailing space is easy to arrive at by pasting.
        $this->getJson('/api/memos?q='.urlencode('  dentist  '))->assertOk();

        $this->assertSame('dentist', $this->repository->lastQuery);
    }

    public function test_an_oversized_or_null_byte_query_is_rejected(): void
    {
        $this->getJson('/api/memos?q='.str_repeat('a', ListMemosRequest::MAX_QUERY_LENGTH + 1))
            ->assertStatus(422)
            ->assertJsonValidationErrors('q');

        // libpq truncates a bound parameter at the first NUL, so without this the search
        // would quietly run against a prefix of what was typed and the page would show
        // results for a query nobody asked for.
        $this->getJson('/api/memos?q='.urlencode("dentist\0ignored"))
            ->assertStatus(422)
            ->assertJsonValidationErrors('q');

        // Neither rejected request reached the database. Asserted before the passing case
        // below, since that one legitimately sets this.
        $this->assertFalse($this->repository->searched);

        // Exactly at the cap passes, so the boundary is a cap and not an off-by-one.
        $this->getJson('/api/memos?q='.str_repeat('a', ListMemosRequest::MAX_QUERY_LENGTH))
            ->assertOk();
    }

    public function test_the_query_and_the_limit_are_honoured_together(): void
    {
        // The cap has to bound a filtered page as well as an unfiltered one -- the rows
        // carry full transcripts either way, and searching is the request most likely to
        // be scripted.
        $this->getJson('/api/memos?q=dentist&limit=10')->assertOk();

        $this->assertSame('dentist', $this->repository->lastQuery);
        $this->assertSame(10, $this->repository->lastLimit);

        $this->getJson('/api/memos?q=dentist')->assertOk();
        $this->assertSame(ListMemosRequest::DEFAULT_LIMIT, $this->repository->lastLimit);

        // A bad limit is still a 422 with a filter attached; the filter must not become a
        // way around the cap.
        $this->getJson('/api/memos?q=dentist&limit='.(ListMemosRequest::MAX_LIMIT + 1))
            ->assertStatus(422)
            ->assertJsonValidationErrors('limit');
    }

    public function test_a_filtered_list_renders_the_same_row_shape_as_an_unfiltered_one(): void
    {
        $this->repository->rows = [$this->memo('019fb4ef-0d71-7011-b678-0cb4004dc2a7', 'call the dentist')];

        $this->getJson('/api/memos?q=dentist')
            ->assertOk()
            ->assertJsonCount(1, 'memos')
            // MEMO-18 replaces polled rows by id, and it polls the filtered list too, so
            // a field that appeared only when unfiltered would break that reconciliation.
            ->assertJsonStructure([
                'memos' => [[
                    'id', 'source', 'status', 'transcript', 'title',
                    'summary', 'tags', 'duration_ms', 'last_error', 'created_at',
                ]],
            ]);
    }

    public function test_a_filtered_list_is_never_cached_either(): void
    {
        // Same reason as the unfiltered list: every poll exists because the answer may
        // have changed, and a cached filtered page would freeze a search mid-transcription.
        $response = $this->getJson('/api/memos?q=dentist');

        $this->assertStringContainsString(
            'no-store',
            (string) $response->headers->get('Cache-Control'),
        );
    }

    private function memo(string $id, string $transcript): Memo
    {
        return new Memo(
            id: $id,
            source: Memo::SOURCE_TEXT,
            status: 'ready',
            transcript: $transcript,
            title: 'Dentist',
            summary: 'A reminder to call the dentist.',
            tags: ['dentist', 'health'],
            durationMs: 4200,
            lastError: null,
            createdAt: '2026-07-31T09:00:00.000Z',
        );
    }
}
