<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Contracts\AudioStorage;
use App\Http\Requests\ListMemosRequest;
use App\Http\Requests\StoreMemoRequest;
use App\Repositories\MemoRepository;
use App\Services\Memos\Memo;
use Illuminate\Http\UploadedFile;
use Tests\Support\FakeMemoRepository;
use Tests\Support\RecordingAudioStorage;
use Tests\TestCase;

/**
 * The decisions MEMO-06 and MEMO-10 make that do not depend on the driver. The SQL
 * itself -- ordering, to_jsonb over a real text[], the generated tsvector column --
 * needs a live Postgres and belongs to MEMO-25; see FakeMemoRepository for why the
 * seam is drawn here.
 */
final class MemoEndpointsTest extends TestCase
{
    private FakeMemoRepository $repository;

    private RecordingAudioStorage $storage;

    /** Upload temp files created by a test, removed afterwards. @var list<string> */
    private array $temporaryFiles = [];

    protected function setUp(): void
    {
        parent::setUp();

        $this->repository = new FakeMemoRepository;
        $this->app->instance(MemoRepository::class, $this->repository);

        // Bound by interface, which is the same seam AppServiceProvider swaps at --
        // so what these tests exercise is the wiring the container actually resolves
        // rather than a service constructed by hand.
        $this->storage = new RecordingAudioStorage;
        $this->app->instance(AudioStorage::class, $this->storage);
    }

    protected function tearDown(): void
    {
        foreach ($this->temporaryFiles as $path) {
            @unlink($path);
        }

        parent::tearDown();
    }

    public function test_posting_text_writes_a_queued_text_memo_and_returns_it_with_its_id(): void
    {
        $response = $this->postJson('/api/memos', ['text' => 'Call the dentist on Tuesday']);

        $response->assertCreated()
            ->assertJsonPath('memo.source', 'text')
            // queued, not ready. The worker still owes this row its enrichment pass.
            ->assertJsonPath('memo.status', 'queued')
            ->assertJsonPath('memo.transcript', 'Call the dentist on Tuesday')
            ->assertJsonPath('memo.title', null)
            ->assertJsonPath('memo.tags', [])
            ->assertJsonPath('memo.duration_ms', null)
            // The full field set, asserted as a whole: MEMO-18 replaces polled rows
            // by id against the object this response produced, so a field appearing
            // in one and not the other is the bug that assertion exists to catch.
            ->assertJsonStructure([
                'memo' => [
                    'id', 'source', 'status', 'transcript', 'title',
                    'summary', 'tags', 'duration_ms', 'last_error', 'created_at',
                ],
            ]);

        $this->assertCount(1, $this->repository->inserted);
        $insert = $this->repository->inserted[0];

        $this->assertSame(Memo::SOURCE_TEXT, $insert['source']);
        $this->assertSame(Memo::STATUS_QUEUED, $insert['status']);
        // The typed text is the transcript, which is what tells the worker no
        // transcription is owed.
        $this->assertSame('Call the dentist on Tuesday', $insert['transcript']);

        // The id was generated by PHP and travelled back out on the 201 -- the whole
        // reason 001_init.sql gives `id` no column default.
        $this->assertSame($insert['id'], $response->json('memo.id'));
        $this->assertSame('7', $insert['id'][14], 'The id must be a UUIDv7.');
    }

    public function test_a_missing_blank_or_oversized_text_is_rejected_and_writes_nothing(): void
    {
        $this->postJson('/api/memos', [])
            ->assertStatus(422)
            ->assertJsonValidationErrors('text');

        // Whitespace only. Trimmed before the rules run, so `min:1` is what refuses
        // it -- a memo whose transcript is three spaces would reach the worker,
        // transcribe to nothing and enrich to nothing.
        $this->postJson('/api/memos', ['text' => "  \n\t "])
            ->assertStatus(422)
            ->assertJsonValidationErrors('text');

        $this->postJson('/api/memos', ['text' => str_repeat('a', StoreMemoRequest::MAX_TEXT_LENGTH + 1)])
            ->assertStatus(422)
            ->assertJsonValidationErrors('text');

        // A rejected request must not have reached the database.
        $this->assertSame([], $this->repository->inserted);
    }

    public function test_a_null_byte_inside_the_text_is_refused_rather_than_silently_truncated(): void
    {
        // The bug this pins: libpq passes bound parameters as C strings, so without
        // this rule the value is cut at the first NUL before Postgres -- which would
        // have rejected it -- ever sees it. Confirmed against a live database before
        // the rule existed: this exact body answered 201 with a transcript of "a".
        $this->postJson('/api/memos', ['text' => "a\0b"])
            ->assertStatus(422)
            ->assertJsonValidationErrors('text');

        $this->assertSame([], $this->repository->inserted);

        // A NUL at either edge was already handled, and by something incidental --
        // PHP's default trim charlist contains "\0", so prepareForValidation strips
        // it and `required` refuses what is left. Asserted so that a later change to
        // that trim cannot quietly reopen the interior case's smaller cousin.
        $this->postJson('/api/memos', ['text' => "\0"])
            ->assertStatus(422)
            ->assertJsonValidationErrors('text');
    }

    public function test_surrounding_whitespace_is_trimmed_from_the_stored_transcript(): void
    {
        $this->postJson('/api/memos', ['text' => '   Milk, eggs, bread   '])
            ->assertCreated()
            ->assertJsonPath('memo.transcript', 'Milk, eggs, bread');

        $this->assertSame('Milk, eggs, bread', $this->repository->inserted[0]['transcript']);
    }

    public function test_the_length_cap_counts_characters_rather_than_bytes(): void
    {
        // Exactly at the cap in characters, four times over it in bytes. Rejecting
        // this would make the limit mean something different for anyone not writing
        // in ASCII.
        $this->postJson('/api/memos', ['text' => str_repeat('あ', StoreMemoRequest::MAX_TEXT_LENGTH)])
            ->assertCreated();
    }

    public function test_posting_a_recording_writes_a_queued_voice_memo_and_returns_it(): void
    {
        $response = $this->post('/api/memos', [
            StoreMemoRequest::AUDIO_FIELD => $this->recording(self::containers()['Chrome']['bytes']),
        ]);

        $response->assertCreated()
            ->assertJsonPath('memo.source', 'voice')
            ->assertJsonPath('memo.status', 'queued')
            // No transcript yet, which is what the worker reads as "this row owes a
            // transcription", and what MemoList renders as "No transcript yet."
            ->assertJsonPath('memo.transcript', null)
            // The same field set a text memo answers with, asserted for the same reason
            // it is asserted there: MEMO-18 replaces polled rows by id against the
            // object this response produced, and the frontend prepends both kinds of
            // memo to one list. A voice-only field here would break that reconciliation
            // -- which is also why `audio_path` is not in the projection at all.
            ->assertJsonStructure([
                'memo' => [
                    'id', 'source', 'status', 'transcript', 'title',
                    'summary', 'tags', 'duration_ms', 'last_error', 'created_at',
                ],
            ]);

        $this->assertCount(1, $this->repository->inserted);
        $insert = $this->repository->inserted[0];

        $this->assertSame(Memo::SOURCE_VOICE, $insert['source']);
        $this->assertSame(Memo::STATUS_QUEUED, $insert['status']);
        $this->assertNull($insert['transcript']);

        // The row points at a key, and the bytes are under that key. This is the whole
        // contract between the API and the Python worker: it resolves `audio_path`
        // against its own AUDIO_DIR on the shared volume (MEMO-12) and opens whatever
        // it finds.
        $this->assertSame(
            self::containers()['Chrome']['bytes'],
            $this->storage->blobs[(string) $insert['audio_path']] ?? null,
        );

        $this->assertSame($insert['id'], $response->json('memo.id'));
    }

    public function test_every_container_the_three_browsers_produce_is_accepted_and_named_correctly(): void
    {
        // MEMO-10's acceptance is that Chrome, Safari and Firefox all upload
        // successfully. The browsers themselves are Pavel's half of that -- no test can
        // produce real microphone input -- and this is the half that can be pinned here:
        // that the API accepts each of the three containers and records what it actually
        // received rather than what it was told.
        //
        // Firefox is the case that makes it worth doing. It reports WebM from
        // MediaRecorder and produces Ogg, so the mime below is `audio/ogg` while the
        // request said `audio/webm` -- the two genuinely disagree, and the row follows
        // the bytes.
        foreach (self::containers() as $browser => $container) {
            $this->post('/api/memos', [
                StoreMemoRequest::AUDIO_FIELD => $this->recording($container['bytes']),
            ])->assertCreated();

            $insert = end($this->repository->inserted);

            $this->assertSame($container['mime'], $insert['audio_mime'], "{$browser}: stored mime");
            $this->assertSame(
                "{$insert['id']}.{$container['extension']}",
                $insert['audio_path'],
                "{$browser}: storage key",
            );
        }

        $this->assertCount(count(self::containers()), $this->repository->inserted);
    }

    public function test_the_stored_mime_is_sniffed_from_the_bytes_rather_than_read_off_the_request(): void
    {
        // A text file wearing an audio name and an audio Content-Type -- the dishonest
        // version of the Firefox mismatch above, and the case where believing the label
        // is most obviously wrong.
        $this->post('/api/memos', [
            StoreMemoRequest::AUDIO_FIELD => $this->recording('This is plainly not a recording.'),
        ])->assertCreated();

        $insert = $this->repository->inserted[0];

        $this->assertSame('text/plain', $insert['audio_mime']);

        // And the storage key follows the sniffed type rather than the name the client
        // chose, because that name is the one thing in this request nobody vouches for
        // and it would otherwise become part of a filesystem path.
        $this->assertSame("{$insert['id']}.txt", $insert['audio_path']);

        // Note what this test is *not* asserting: that the upload was refused. It was
        // accepted, and MEMO-11 is the task that rejects it -- "a .txt renamed to .webm
        // is rejected" is that task's acceptance criterion, and the allowlist it needs
        // is built on exactly the sniffed value pinned above.
    }

    public function test_text_and_audio_in_one_request_are_refused_rather_than_merged(): void
    {
        // There is no honest reading of both: the text could be the transcript of the
        // recording or a second memo, and picking one would silently discard whichever
        // the caller meant. Nothing sends both today, so this is here so that a client
        // which starts to finds out on the first request.
        $this->post('/api/memos', [
            'text' => 'Call the dentist',
            StoreMemoRequest::AUDIO_FIELD => $this->recording(self::containers()['Chrome']['bytes']),
        ])->assertStatus(422);

        $this->assertSame([], $this->repository->inserted);
        $this->assertSame([], $this->storage->written);
    }

    public function test_a_request_carrying_neither_text_nor_audio_names_both(): void
    {
        // Relaxing `text` from required to required_without is the change that could
        // quietly make an empty POST succeed. Both fields are named so the message says
        // what the route accepts rather than only mentioning the older half of it.
        $this->postJson('/api/memos', [])
            ->assertStatus(422)
            ->assertJsonValidationErrors(['text', StoreMemoRequest::AUDIO_FIELD]);

        $this->assertSame([], $this->repository->inserted);
    }

    public function test_an_empty_text_part_alongside_a_recording_is_absence_rather_than_a_conflict(): void
    {
        // A multipart body with both an empty `text` and the file. ConvertEmptyStringsToNull
        // makes that a null which is *present*, which is not the same as absent -- before
        // `nullable` this answered 422 "The text field must be a string." to a request
        // whose only content was a recording.
        $this->post('/api/memos', [
            'text' => '',
            StoreMemoRequest::AUDIO_FIELD => $this->recording(self::containers()['Chrome']['bytes']),
        ])->assertCreated()->assertJsonPath('memo.source', 'voice');

        $this->assertSame(Memo::SOURCE_VOICE, $this->repository->inserted[0]['source']);
        $this->assertNull($this->repository->inserted[0]['transcript']);
    }

    public function test_an_empty_text_on_its_own_is_still_refused(): void
    {
        // The other half of `nullable`, and the one worth pinning: it must not have
        // turned an empty memo into an accepted one. required_without is implicit, so it
        // still judges a null -- but that is a property of Laravel's rule ordering rather
        // than something obvious from reading the list.
        foreach ([['text' => ''], ['text' => null], ['text' => '   ']] as $body) {
            $this->postJson('/api/memos', $body)
                ->assertStatus(422)
                ->assertJsonValidationErrors('text');
        }

        $this->assertSame([], $this->repository->inserted);
    }

    public function test_an_audio_field_that_is_not_a_file_is_refused(): void
    {
        // `audio` as a plain string satisfies required_without and nothing else. Worth
        // pinning because the failure would not be a 422: it would reach
        // StoreMemoRequest::audio(), find no UploadedFile, return null, and the
        // controller would then treat a request with no `text` as a text memo.
        $this->postJson('/api/memos', [StoreMemoRequest::AUDIO_FIELD => 'not-a-file'])
            ->assertStatus(422)
            ->assertJsonValidationErrors(StoreMemoRequest::AUDIO_FIELD);

        $this->assertSame([], $this->repository->inserted);
    }

    public function test_a_recording_the_volume_will_not_take_is_a_500_rather_than_a_rejected_memo(): void
    {
        $this->storage->failOnPut = true;

        // An unwritable volume is not something the person recording can fix, and
        // answering 4xx would tell them their memo was the problem. See
        // App\Exceptions\StorageException, which exists to draw that line, and MEMO-17
        // for the failure UX this eventually gets.
        $this->post('/api/memos', [
            StoreMemoRequest::AUDIO_FIELD => $this->recording(self::containers()['Chrome']['bytes']),
        ])->assertStatus(500);

        $this->assertSame([], $this->repository->inserted, 'No row may exist without its audio.');
    }

    public function test_listing_renders_every_field_and_keeps_the_order_it_was_given(): void
    {
        $this->repository->rows = [
            $this->memo('019fb4ef-0d71-7011-b678-0cb4004dc2a7', 'the newer one'),
            $this->memo('019fb4ee-0d71-7011-b678-0cb4004dc2a7', 'the older one'),
        ];

        $response = $this->getJson('/api/memos');

        $response->assertOk()
            ->assertJsonCount(2, 'memos')
            ->assertJsonPath('memos.0.transcript', 'the newer one')
            ->assertJsonPath('memos.1.transcript', 'the older one')
            ->assertJsonPath('memos.0.tags', ['dentist', 'health'])
            ->assertJsonPath('memos.0.duration_ms', 4200)
            ->assertJsonPath('memos.0.last_error', null)
            ->assertJsonPath('memos.0.created_at', '2026-07-31T09:00:00.000Z');

        // Newest-first is `ORDER BY created_at DESC` in the repository, verified
        // against a live Postgres rather than here: this asserts only that nothing
        // between the query and the JSON reorders the rows.
        $this->assertSame(ListMemosRequest::DEFAULT_LIMIT, $this->repository->lastLimit);
    }

    public function test_a_polled_list_is_never_cached(): void
    {
        $response = $this->getJson('/api/memos');

        $this->assertStringContainsString(
            'no-store',
            (string) $response->headers->get('Cache-Control'),
        );
    }

    public function test_limit_is_honoured_bounded_and_defaulted(): void
    {
        $this->getJson('/api/memos?limit=10')->assertOk();
        $this->assertSame(10, $this->repository->lastLimit);

        // Set but empty is "unset", the same reading App\Support\Env applies to the
        // environment: a query string built with no limit chosen must not 422.
        $this->getJson('/api/memos?limit=')->assertOk();
        $this->assertSame(ListMemosRequest::DEFAULT_LIMIT, $this->repository->lastLimit);

        // Rejected rather than clamped. A clamped 5000 answers 200 with 200 rows and
        // reads as "there are only 200 memos".
        foreach (['0', '-1', 'abc', '10.5', (string) (ListMemosRequest::MAX_LIMIT + 1)] as $limit) {
            $this->getJson("/api/memos?limit={$limit}")
                ->assertStatus(422)
                ->assertJsonValidationErrors('limit');
        }
    }

    public function test_a_query_reaches_the_search_statement_exactly_as_it_was_typed(): void
    {
        // Whatever the query means is decided by websearch_to_tsquery and by the ILIKE
        // pattern, both in SQL. Nothing between the query string and the bound parameter
        // may rewrite it -- stripping the quotes from a phrase or the minus from an
        // exclusion here would silently turn the two features the search advertises into
        // a bag of words.
        foreach (['dentist', '"call the dentist"', 'dentist -thursday', 'reorg', '50%'] as $query) {
            $this->getJson('/api/memos?q='.urlencode($query))->assertOk();

            $this->assertTrue($this->repository->searched);
            $this->assertSame($query, $this->repository->lastQuery);
        }
    }

    public function test_the_query_is_echoed_back_so_a_stale_response_can_be_discarded(): void
    {
        // Searching is debounced and polled, so a response can arrive after the box has
        // moved on. The client compares this key to decide whether the rows it just
        // received still belong on screen.
        $this->getJson('/api/memos?q=dentist')
            ->assertOk()
            ->assertJsonPath('query', 'dentist');

        // Always present, so the client reads one key rather than branching on whether it
        // exists.
        $this->getJson('/api/memos')
            ->assertOk()
            ->assertJsonPath('query', null);
    }

    public function test_a_blank_query_is_no_filter_rather_than_a_filter_matching_everything(): void
    {
        // Three spellings of "the user has not typed anything". The frontend's search box
        // is empty most of the time, so these are the ordinary request: `?q=` is what a
        // query string built around an empty box looks like, and %20 is what one space in
        // it looks like.
        foreach (['/api/memos', '/api/memos?q=', '/api/memos?q=%20%20'] as $url) {
            $this->getJson($url)->assertOk()->assertJsonPath('query', null);

            // The unfiltered statement, which is the one with the index scan. A filter
            // matching everything would answer the same rows and lose that plan.
            $this->assertFalse($this->repository->searched);
            $this->assertNull($this->repository->lastQuery);
        }
    }

    public function test_a_query_that_is_falsy_as_a_string_is_still_a_query(): void
    {
        // '0' is falsy in PHP and in JavaScript, so both halves of this feature have a
        // truthiness test one refactor away from turning a search for "0" into no filter at
        // all -- answering the entire list and looking like the search silently broke.
        // Reachable: "0" is what you type looking for a memo about a zero.
        $this->getJson('/api/memos?q=0')
            ->assertOk()
            ->assertJsonPath('query', '0');

        $this->assertTrue($this->repository->searched);
        $this->assertSame('0', $this->repository->lastQuery);
    }

    public function test_a_rejected_filter_says_so_in_words_a_reader_can_act_on(): void
    {
        // The frontend renders this message verbatim (web/src/api/memos.js), and a paste
        // into the filter box is how a 422 gets reached without meaning to. Unnamed, the
        // field reads "The q field must not be greater than 200 characters." -- a sentence
        // about a query-string parameter, shown to somebody looking at a box labelled
        // "Filter memos".
        $response = $this->getJson('/api/memos?q='.str_repeat('a', ListMemosRequest::MAX_QUERY_LENGTH + 1));

        $response->assertStatus(422);

        $this->assertStringContainsString('filter', (string) $response->json('message'));
        $this->assertStringNotContainsString('q field', (string) $response->json('message'));
    }

    public function test_surrounding_whitespace_is_trimmed_from_the_query(): void
    {
        // So the ILIKE pattern is `%dentist%` rather than `%  dentist  %`, which would
        // match nothing. Trailing space is easy to arrive at by pasting.
        $this->getJson('/api/memos?q='.urlencode('  dentist  '))->assertOk();

        $this->assertSame('dentist', $this->repository->lastQuery);
    }

    public function test_an_oversized_or_null_byte_query_is_rejected(): void
    {
        $this->getJson('/api/memos?q='.str_repeat('a', ListMemosRequest::MAX_QUERY_LENGTH + 1))
            ->assertStatus(422)
            ->assertJsonValidationErrors('q');

        // libpq truncates a bound parameter at the first NUL, so without this the search
        // would quietly run against a prefix of what was typed and the page would show
        // results for a query nobody asked for.
        $this->getJson('/api/memos?q='.urlencode("dentist\0ignored"))
            ->assertStatus(422)
            ->assertJsonValidationErrors('q');

        // Neither rejected request reached the database. Asserted before the passing case
        // below, since that one legitimately sets this.
        $this->assertFalse($this->repository->searched);

        // Exactly at the cap passes, so the boundary is a cap and not an off-by-one.
        $this->getJson('/api/memos?q='.str_repeat('a', ListMemosRequest::MAX_QUERY_LENGTH))
            ->assertOk();
    }

    public function test_the_query_and_the_limit_are_honoured_together(): void
    {
        // The cap has to bound a filtered page as well as an unfiltered one -- the rows
        // carry full transcripts either way, and searching is the request most likely to
        // be scripted.
        $this->getJson('/api/memos?q=dentist&limit=10')->assertOk();

        $this->assertSame('dentist', $this->repository->lastQuery);
        $this->assertSame(10, $this->repository->lastLimit);

        $this->getJson('/api/memos?q=dentist')->assertOk();
        $this->assertSame(ListMemosRequest::DEFAULT_LIMIT, $this->repository->lastLimit);

        // A bad limit is still a 422 with a filter attached; the filter must not become a
        // way around the cap.
        $this->getJson('/api/memos?q=dentist&limit='.(ListMemosRequest::MAX_LIMIT + 1))
            ->assertStatus(422)
            ->assertJsonValidationErrors('limit');
    }

    public function test_a_filtered_list_renders_the_same_row_shape_as_an_unfiltered_one(): void
    {
        $this->repository->rows = [$this->memo('019fb4ef-0d71-7011-b678-0cb4004dc2a7', 'call the dentist')];

        $this->getJson('/api/memos?q=dentist')
            ->assertOk()
            ->assertJsonCount(1, 'memos')
            // MEMO-18 replaces polled rows by id, and it polls the filtered list too, so
            // a field that appeared only when unfiltered would break that reconciliation.
            ->assertJsonStructure([
                'memos' => [[
                    'id', 'source', 'status', 'transcript', 'title',
                    'summary', 'tags', 'duration_ms', 'last_error', 'created_at',
                ]],
            ]);
    }

    public function test_a_filtered_list_is_never_cached_either(): void
    {
        // Same reason as the unfiltered list: every poll exists because the answer may
        // have changed, and a cached filtered page would freeze a search mid-transcription.
        $response = $this->getJson('/api/memos?q=dentist');

        $this->assertStringContainsString(
            'no-store',
            (string) $response->headers->get('Cache-Control'),
        );
    }

    /**
     * The opening bytes of each container MediaRecorder actually produces, one per
     * browser, so the sniffing these tests are about has something real to sniff.
     *
     * Headers rather than recordings: finfo reads the magic at the start of a file and
     * nothing after it, so a real memo would add a megabyte to the repository to prove
     * the same thing. Every mime below was read off this image's libmagic rather than
     * assumed, and they are the ones MEMO-11's page predicts -- note that audio-only
     * WebM and MP4 both sniff as **video/** types, which is why an allowlist of
     * `audio/*` would reject every genuine recording.
     *
     * A method rather than a const because the Ogg page below has to be assembled, and
     * that is the point: written out as one literal it was two bytes too long, which
     * pushed `OpusHead` off the offset libmagic reads and sniffed the whole thing as
     * application/octet-stream. A header built from its named fields cannot drift like
     * that, and it says what the bytes are.
     *
     * @return array<string, array{bytes: string, mime: string, extension: string}>
     */
    private static function containers(): array
    {
        return [
            // Chrome and Edge: an EBML header whose DocType is "webm". The DocType is
            // what decides it -- the same header saying "matroska" sniffs as
            // video/x-matroska.
            'Chrome' => [
                'bytes' => "\x1a\x45\xdf\xa3\x01\x00\x00\x00\x00\x00\x00\x1f"
                    ."\x42\x86\x81\x01\x42\xf7\x81\x01\x42\xf2\x81\x04\x42\xf3\x81\x08"
                    ."\x42\x82\x84webm\x42\x87\x81\x02\x42\x85\x81\x02",
                'mime' => 'video/webm',
                'extension' => 'webm',
            ],

            // Firefox: Ogg, even when MediaRecorder reported WebM (Mozilla bug 1501308).
            // One Ogg page: the 27-byte header -- capture pattern, version 0, a
            // beginning-of-stream flag, then 20 bytes of granule position, serial,
            // sequence and CRC that no sniffer reads -- then a one-entry segment table,
            // then the Opus identification packet that gives it `audio/` rather than
            // `application/ogg`.
            'Firefox' => [
                'bytes' => 'OggS'."\x00\x02".str_repeat("\x00", 20)."\x01\x1e"
                    .'OpusHead'."\x01\x01\x38\x01\x80\xbb\x00\x00\x00\x00\x00",
                'mime' => 'audio/ogg',
                'extension' => 'ogg',
            ],

            // Safari: MP4 or fragmented MP4, recognised from the `ftyp` box.
            'Safari' => [
                'bytes' => "\x00\x00\x00\x20".'ftypisom'."\x00\x00\x02\x00".'isomiso2avc1mp41',
                'mime' => 'video/mp4',
                'extension' => 'mp4',
            ],
        ];
    }

    /**
     * A multipart upload of exactly these bytes, always announced as `memo.webm` and
     * `audio/webm` no matter what is inside it.
     *
     * A real UploadedFile in test mode rather than UploadedFile::fake(), and the
     * difference is the entire point of the tests above. Laravel's testing double
     * overrides getMimeType() to guess from the *filename* -- so against a fake, an
     * assertion that this endpoint sniffs its input passes whether it sniffs or not.
     * Found the honest way: the first version of these tests used the fake, and the one
     * asserting that a text file is recorded as text/plain answered video/webm, which is
     * the filename talking. Symfony's UploadedFile leaves getMimeType() as finfo over
     * the bytes and puts the request's label on getClientMimeType(), where nothing reads
     * it.
     *
     * The fixed name and label are what make every one of these a mismatch case by
     * construction: a Firefox recording really does arrive labelled WebM, so the tests
     * cannot pass by accident on a client that happened to be honest.
     *
     * The file is left on disk for tearDown. `$test: true` is what keeps
     * is_uploaded_file() out of it -- without it the framework treats the path as not
     * having come from an upload and the `file` rule fails every one of these.
     */
    private function recording(string $contents): UploadedFile
    {
        $path = tempnam(sys_get_temp_dir(), 'memo-recording-');

        $this->assertIsString($path);
        file_put_contents($path, $contents);
        $this->temporaryFiles[] = $path;

        return new UploadedFile($path, 'memo.webm', 'audio/webm', test: true);
    }

    private function memo(string $id, string $transcript): Memo
    {
        return new Memo(
            id: $id,
            source: Memo::SOURCE_TEXT,
            status: 'ready',
            transcript: $transcript,
            title: 'Dentist',
            summary: 'A reminder to call the dentist.',
            tags: ['dentist', 'health'],
            durationMs: 4200,
            lastError: null,
            createdAt: '2026-07-31T09:00:00.000Z',
        );
    }
}
